### ISSUE TITLE
往事不要再提人生已多风雨

### ISSUE THREAD

**Issue by hytvszz** [hytvszz/hytvszz.github.io#131]
https://www.heyzhen.com/%E5%BE%80%E4%BA%8B%E4%B8%8D%E8%A6%81%E5%86%8D%E6%8F%90%E4%BA%BA%E7%94%9F%E5%B7%B2%E5%A4%9A%E9%A3%8E%E9%9B%A8/ 

 今天好哥们王部长忽然过来跟我说，家里给安排了一个相亲，然后还发了妹子的豆瓣文章给我看。不得不佩服王部长的情报工作，还没见面认识就把人家豆瓣都人肉了出来。

妹子是一个在美国留学几年的文青，妹子的豆瓣文章字里行间流露着对纽约自由生活的热爱，当然也包括pub的夜生活，还凡尔赛了一下自己的各种dating。王部长深感忧虑，虽然感觉他几段感情都从yp开始，但是他还是一个传统的人（exo me？？此处我也不知道我在说什么）。王部长是山西人，骨子里可能还是希望夫唱妇随的简单生活。估计这也是他对美国妹子这样的看起来像玩咖的有一点担忧。

王部长问我说，你能接受这样的吗？我毫不犹豫的肯定。在我看来，一个人的过去属于她自己，把握两个人的当下，和可期的未来，才是最重要的，或者说是有意义的。如果两个人聊起什么话题，她分享了过去有趣的经历，那也是很有意思的。但是如果她不说，我甚至也根本不想去问。王部长摇摇头说，还是你豁达，我是不可以。我说那就再找乖妹子吧，乖妹子还是更多的。然后我就对自己的话陷入了思考。

女友的过去，或者朋友的过去，对你来说重要吗？不管他交往了多少男友，之前玩的多疯，在我看来那都是过去了，当然曾经沧海难为水，或许你找了一个定时炸弹，但是毕竟感情也不是一蹴而就的。你们交往的那些时光里，你对她的了解，我觉得是更重要的，人都在变的。如果你没有决定的决心和勇气，那你多半也不会再迈出最后一步。丰富的过去，在我看来，是

**Comment by Cecilia819818** [comment]
哎呀！天天穿着hoddy嘻嘻哈哈的，原来两性观那么成熟开明呀！怎么办，一不小心又capture到优秀点了！
